// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/SkyDDDog/demo03",
        "contact": {
            "name": "二火",
            "url": "https://github.com/SkyDDDog",
            "email": "lear_yd@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/note": {
            "post": {
                "description": "添加一条待办事项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NoteController"
                ],
                "summary": "新增待办",
                "parameters": [
                    {
                        "description": "note",
                        "name": "string",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/note/all": {
            "delete": {
                "description": "删除 所有 事项",
                "tags": [
                    "NoteController"
                ],
                "summary": "删除事项",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/note/done": {
            "put": {
                "description": "将 多条 代办事项设置为已完成",
                "tags": [
                    "NoteController"
                ],
                "summary": "完成待办",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除 所有已经完成 事项",
                "tags": [
                    "NoteController"
                ],
                "summary": "删除事项",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/note/done/{id}": {
            "put": {
                "description": "将 一条 代办事项设置为已完成",
                "tags": [
                    "NoteController"
                ],
                "summary": "完成待办",
                "parameters": [
                    {
                        "type": "string",
                        "description": "note",
                        "name": "string",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/note/undo": {
            "put": {
                "description": "将 多条 已完成事项设置为待办",
                "tags": [
                    "NoteController"
                ],
                "summary": "设为待办",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除 所有待办 事项",
                "tags": [
                    "NoteController"
                ],
                "summary": "删除事项",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/note/undo/{id}": {
            "put": {
                "description": "将 一条 已完成事项设置为待办",
                "tags": [
                    "NoteController"
                ],
                "summary": "设为待办",
                "parameters": [
                    {
                        "type": "string",
                        "description": "note",
                        "name": "string",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/note/{id}": {
            "delete": {
                "description": "删除 一条 事项",
                "tags": [
                    "NoteController"
                ],
                "summary": "删除事项",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "string",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test/ping": {
            "get": {
                "description": "测试",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TestController"
                ],
                "summary": "Ping!",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "用户登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserController"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户vo",
                        "name": "string",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserController"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "用户vo",
                        "name": "string",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:1234",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "小黄老师备忘录",
	Description:      "West2-Golang-Demo03",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
