info:
  contact: {}
paths:
  /note:
    get:
      description: 查看所有事项
      parameters:
      - description: pageNum
        in: query
        name: pageNum
        required: true
        type: string
      - description: pageSize
        in: query
        name: pageSIze
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 查看事项
      tags:
      - NoteController
    post:
      consumes:
      - application/json
      description: 添加一条待办事项
      parameters:
      - description: note
        in: body
        name: string
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 新增待办
      tags:
      - NoteController
  /note/{id}:
    delete:
      description: 删除 一条 事项
      parameters:
      - description: id
        in: path
        name: string
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除事项
      tags:
      - NoteController
  /note/all:
    delete:
      description: 删除 所有 事项
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除事项
      tags:
      - NoteController
  /note/done:
    delete:
      description: 删除 所有已经完成 事项
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除事项
      tags:
      - NoteController
    get:
      description: 查看所有待办事项
      parameters:
      - description: pageNum
        in: query
        name: pageNum
        required: true
        type: string
      - description: pageSize
        in: query
        name: pageSIze
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 查看事项
      tags:
      - NoteController
    put:
      description: 将 多条 代办事项设置为已完成
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 完成待办
      tags:
      - NoteController
  /note/done/{content}:
    get:
      description: 输入关键词查询事项
      parameters:
      - description: content
        in: path
        name: content
        required: true
        type: string
      - description: pageNum
        in: query
        name: pageNum
        required: true
        type: string
      - description: pageSize
        in: query
        name: pageSIze
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 查询事项
      tags:
      - NoteController
  /note/done/{id}:
    put:
      description: 将 一条 代办事项设置为已完成
      parameters:
      - description: note
        in: path
        name: string
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 完成待办
      tags:
      - NoteController
  /note/undo:
    delete:
      description: 删除 所有待办 事项
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除事项
      tags:
      - NoteController
    put:
      description: 将 多条 已完成事项设置为待办
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 设为待办
      tags:
      - NoteController
  /note/undo/{id}:
    put:
      description: 将 一条 已完成事项设置为待办
      parameters:
      - description: note
        in: path
        name: string
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 设为待办
      tags:
      - NoteController
  /test/ping:
    get:
      consumes:
      - application/json
      description: 测试
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Ping!
      tags:
      - TestController
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户vo
        in: body
        name: string
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户登录
      tags:
      - UserController
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 用户vo
        in: body
        name: string
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 创建用户
      tags:
      - UserController
swagger: "2.0"
